### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vmario89** [aconz2/inkscape-extension-flip#1]
Hi,
just found your repo. Thanks for sharing your ideas with the community.
I wanted to ask you if you are aware about a quite similar extension from https://inkscape.org/~jeko/%E2%98%85mirror. Or does flip extension something different?

regards, Mario

**Comment by aconz2** [comment]
Yes slightly different, maybe I'll try to reword the description.

This extension only operates on a single path (or a selection of paths but all individually) by flipping it about the _imaginary_ line that goes from the paths first node to its last node.

Does that clarify?

**Comment by vmario89** [comment]
aaah indeed this is very cool and useful. Great feature!

**Comment by vmario89** [comment]
before:
![grafik](https://user-images.githubusercontent.com/5631071/114210020-9410bd80-995f-11eb-8252-757779522965.png)
duplicating the Path using CTRL + D once + running your extension:
![grafik](https://user-images.githubusercontent.com/5631071/114209996-8d824600-995f-11eb-8cd0-f82949075b42.png)
